name: bcsir
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.11
  chewie: ^1.3.0
  cupertino_icons: ^1.0.6
  permission_handler: ^11.1.0
  image_picker: ^1.0.0
  path_provider: ^2.0.13
  firebase_auth: ^5.3.1  # Latest compatible version
  firebase_core: ^3.6.0   # Updated core Firebase functionality
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true








